services:
  shopware:
    # use either tag "latest" or any other version like "6.5.3.0", ...
    image: dockware/flex:latest
    container_name: {{applicationName.paramCase()}}
    ports:
      - "8055:80"
      - "2222:22"
      - "8888:8888"
      - "9999:9999"
    volumes:
      - "{{applicationName.paramCase()}}_volume:/var/www/html"

    networks:
      - web
    environment:
      # default = 0, recommended to be OFF for frontend devs
      - XDEBUG_ENABLED=1
      # default = latest PHP, optional = specific version
      - PHP_VERSION=8.2

  adminer: # to open it :http://localhost:8080, server: db, user:root, pwd:root
    image: adminer
    container_name: {{applicationName.paramCase()}}_adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - web

volumes:
  {{applicationName.paramCase()}}_volume:
    driver: local

networks:
  web:
    external: false
